# -*- coding: utf-8 -*-
"""app/streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkdGHjNc7j3kyxIYYAS5ZtcV2gVGCIRJ
"""

# app/streamlit_app.py
import streamlit as st
from PIL import Image
import tempfile
import os
from src.predict import load_model, predict_image

MODEL_PATH = "models/vtuber_model.pth"

@st.cache_resource
def load():
    model, class_names, device = load_model(MODEL_PATH)
    return model, class_names, device

st.set_page_config(page_title="VTuber vs Human (Image-only)")
st.title("VTuber vs Human — Image-only classifier")
st.write("Upload or paste an image to classify whether it's a VTuber avatar or a real human.")

uploaded = st.file_uploader("Choose an image", type=["jpg","jpeg","png"])
if uploaded:
    img = Image.open(uploaded).convert("RGB")
    st.image(img, caption="Input image", use_column_width=True)
    st.write("Predicting...")
    model, class_names, device = load()
    res = predict_image(model, class_names, device, img)
    label = res['label']
    conf = res['confidence']
    st.metric("Prediction", label, f"{conf*100:.1f}%")
    st.write("All class probabilities:")
    for name, p in zip(class_names, res['probs']):
        st.write(f"- {name}: {p*100:.2f}%")
else:
    st.info("Upload an image (face or avatar). For best results, crop to the face region.")