# -*- coding: utf-8 -*-
"""create_vtuber_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGstpk2sKVEvP6U-O6w84RpjWnaYz07I
"""

import os
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

# -------------------
# Paths
# -------------------
DATASET_DIR = "dataset"  # Your dataset folder in repo root
MODEL_PATH = "vtuber_model.h5"
IMAGE_SIZE = (224, 224)
BATCH_SIZE = 16
EPOCHS = 10  # Increase if you want better accuracy

# -------------------
# Data generators
# -------------------
datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2,
    horizontal_flip=True,
    rotation_range=20,
    zoom_range=0.15
)

train_gen = datagen.flow_from_directory(
    DATASET_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="training"
)

val_gen = datagen.flow_from_directory(
    DATASET_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    subset="validation"
)

# -------------------
# Build MobileNetV2 Model
# -------------------
base_model = MobileNetV2(weights="imagenet", include_top=False, input_shape=(224,224,3))
x = GlobalAveragePooling2D()(base_model.output)
x = Dense(64, activation="relu")(x)
output = Dense(1, activation="sigmoid")(x)
model = Model(inputs=base_model.input, outputs=output)

model.compile(optimizer=Adam(learning_rate=1e-4),
              loss="binary_crossentropy",
              metrics=["accuracy"])

# -------------------
# Train Model
# -------------------
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS
)

# -------------------
# Save Model
# -------------------
model.save(MODEL_PATH)
print(f"Model saved as {MODEL_PATH}")