# -*- coding: utf-8 -*-
"""src/predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Z-uzmVBwSwEuetobGI6iJdYKIbHxilZ
"""

# src/predict.py
import torch
from PIL import Image
from torchvision import transforms
import numpy as np
import os

def load_model(path, device=None):
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    checkpoint = torch.load(path, map_location=device)
    class_names = checkpoint.get('class_names', ['human','vtuber'])
    # assume resnet50 architecture (must match train)
    from torchvision import models
    model = models.resnet50(pretrained=False)
    in_f = model.fc.in_features
    model.fc = torch.nn.Linear(in_f, len(class_names))
    model.load_state_dict(checkpoint['model_state'])
    model.to(device).eval()
    return model, class_names, device

def preprocess_image(pil_img, img_size=224):
    t = transforms.Compose([
        transforms.Resize((img_size,img_size)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225])
    ])
    return t(pil_img).unsqueeze(0)

def predict_image(model, class_names, device, image_path_or_pil):
    if isinstance(image_path_or_pil, str):
        img = Image.open(image_path_or_pil).convert('RGB')
    else:
        img = image_path_or_pil.convert('RGB')
    x = preprocess_image(img).to(device)
    with torch.no_grad():
        logits = model(x)
        probs = torch.softmax(logits, dim=1).cpu().numpy()[0]
    top_idx = int(probs.argmax())
    return {'label': class_names[top_idx], 'confidence': float(probs[top_idx]), 'probs': probs.tolist()}