# -*- coding: utf-8 -*-
"""src/train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZInMOhhEr0dNiB2GwauwdDizYBu5kaN
"""

# src/train.py
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models
from tqdm import tqdm
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import os

from dataset import make_dataloaders

def build_model(num_classes=2, backbone='resnet50', pretrained=True):
    if backbone == 'resnet50':
        model = models.resnet50(pretrained=pretrained)
        in_f = model.fc.in_features
        model.fc = nn.Linear(in_f, num_classes)
    elif backbone == 'mobilenet_v2':
        model = models.mobilenet_v2(pretrained=pretrained)
        in_f = model.classifier[1].in_features
        model.classifier[1] = nn.Linear(in_f, num_classes)
    else:
        raise ValueError("Unsupported backbone")
    return model

def train_loop(data_dir="data", epochs=8, batch_size=32, lr=1e-4, device=None, save_path="models/vtuber_model.pth"):
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    train_loader, val_loader, class_names = make_dataloaders(data_dir, batch_size=batch_size)
    model = build_model(num_classes=len(class_names)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    best_val_acc = 0.0

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        for imgs, labels in tqdm(train_loader, desc=f"Train Epoch {epoch+1}/{epochs}"):
            imgs = imgs.to(device); labels = labels.to(device)
            optimizer.zero_grad()
            outputs = model(imgs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * imgs.size(0)
        epoch_loss = running_loss / len(train_loader.dataset)

        # validation
        model.eval()
        preds = []
        gts = []
        with torch.no_grad():
            for imgs, labels in val_loader:
                imgs = imgs.to(device)
                outputs = model(imgs)
                p = outputs.argmax(dim=1).cpu().numpy()
                preds.extend(p.tolist())
                gts.extend(labels.numpy().tolist())
        from sklearn.metrics import accuracy_score
        val_acc = accuracy_score(gts, preds)
        print(f"Epoch {epoch+1}: loss={epoch_loss:.4f}, val_acc={val_acc:.4f}")
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            torch.save({'model_state': model.state_dict(), 'class_names': class_names}, save_path)
            print(f"Saved best model to {save_path}")
    print("Training complete. Best val acc:", best_val_acc)
    return save_path